# Generated by Django 3.1.5 on 2021-01-11 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('UK', 'Unknown'), ('Networking Components', (('RT', 'Router'), ('AP', 'Access Point'))), ('Multimedia Devices', (('NS', 'Network-attached Storage'), ('PT', 'Printer'), ('MC', 'Media Center'))), ('User Devices', (('PC', 'Personal Computer'), ('NB', 'Notebook'), ('MB', 'Mobile Phone')))], default='UK', max_length=2)),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.device')),
            ],
        ),
    ]
