# Generated by Django 3.1.5 on 2021-01-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='name',
            field=models.CharField(default='Neznámá URL', max_length=80),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('UK', 'Neznámé'), ('Síťové prvky', (('RT', 'Směrovač'), ('AP', 'Přístupový bod'))), ('Mediální zařízení', (('NS', 'Síťové úložiště'), ('PT', 'Tiskárna'), ('MC', 'Multimediální centrum'))), ('Uživatelská zařízení', (('PC', 'Stolní počítač'), ('NB', 'Notebook'), ('MB', 'Mobilní telefon')))], default='UK', max_length=2),
        ),
    ]
