# Generated by Django 3.1.5 on 2021-01-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210111_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('UK', 'Neznámé'), ('RT', 'Směrovač'), ('AP', 'Přístupový bod'), ('NS', 'Síťové úložiště'), ('PT', 'Tiskárna'), ('MC', 'Multimediální centrum'), ('PC', 'Stolní počítač'), ('NB', 'Notebook'), ('MB', 'Mobilní telefon')], default='UK', max_length=2),
        ),
    ]
