# Generated by Django 3.1.5 on 2021-01-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210111_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.CharField(default='0.0.0.0', max_length=15, unique=True),
        ),
    ]
