# Generated by Django 3.1.5 on 2021-01-12 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210111_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='app.device'),
        ),
    ]
