# Generated by Django 3.1.4 on 2021-01-20 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210112_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='default_url',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_device', to='app.url'),
        ),
    ]
