# Generated by Django 3.1.4 on 2021-01-21 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210121_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='default_url',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_device', to='app.url'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='url',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(),
        ),
    ]
