# Generated by Django 3.1.4 on 2021-01-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210121_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('UK', 'Neznámé'), ('RT', 'Směrovač'), ('SW', 'Přepínač'), ('AP', 'Přístupový bod'), ('NS', 'Síťové úložiště'), ('PT', 'Tiskárna'), ('MC', 'Multimediální centrum'), ('PC', 'Stolní počítač'), ('NB', 'Notebook'), ('MB', 'Mobilní telefon')], default='UK', max_length=2),
        ),
        migrations.AlterField(
            model_name='url',
            name='name',
            field=models.CharField(default='Neznámá URL', max_length=80),
        ),
    ]
